name: 'Merge Conflict Finder'
description: 'Check if there are any unresolved merge conflicts'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'docker://ubuntu:latest'
  entrypoint: 'conflictFinder'
